label: 'UZH BIO392'
tagline: 'Bioinformatics of Sequence Variation'
description: |
  This is the repository for the University of Zurich's undergraduate course in life sciences BIO392 block course.
keywords: UZH, life sciences, baudisgroup
site_domain_name: http://compbiozurich.org
url: 'https://compbiozurich.org'

# The baseurl parameter is an empty string if the site is represented at the root
# of a domain. For project domains on Github it corresponds to the project name.
baseurl: "/UZH-BIO392"

# the site_parent_link parameter is used e.g. for icon links.
site_parent_link: 'https://compbiozurich.org'
github_organisation: compbiozurich

# instructions for processing specific directories
include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".
# The "_posts" collection is created by default.
collections:
  doc:
    output: true
    permalink: /doc/:path/
  people:
    output: true
    permalink: /people/:path/
  howto:
    output: true
    permalink: /howto/:path/
  days:
    output: true
    permalink: /days/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout
nav_cat_blocks:     # comma-separated "label,type,label_visibility"
  general: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

# content of the different navigation blocks
general:
  doc: 'Course Info'
  days: 'Course Days'
  people: Teachers
  howto: 'Examples, Guides & FAQ'
  material: 'Course Material'

related_sites:
  CompbioZurich: "http://www.compbiozurich.org"
  'UZH390 lectures': '/UZH-BIO390/'
  'Baudisgroup at UZH': 'http://info.baudisgroup.org'

github_projects:
  'compbiozurich': 'http://github.com/compbiozurich/'
  'progenetix': 'http://github.com/progenetix/'

# The categories-date-sorted parameter determines the selection of a
# time sorted, year labeled listing template for those categories.
categories-date-sorted:
  - news
# As above, for tags:
tags-date-sorted:
  - days

# Only tags listed here are represented in the tag cloud.
cloud_tags:
  - code
  - contacts
  - documentation
  - exam
  - feedback
  - FAQ
  - Jekyll
  - Markdown
  - website
  - slides
  - data
  - exercises
  - teachers

# additional Jekyll instructions
plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # displayed sidebar links in current category
emptyArray: []          # dummy element for array instantiation
